### ISSUE TITLE
add helpdesk as a initial user

### ISSUE THREAD

**Issue by dianawi** [agent725/peer2product#4]
Right now, J is set as a standard user when one clones a webshop. That is handy because it means he can log in to the user's shop and help out, and the get deleted when the user doesn't need any help anymore. 
But is should bethen  a 'helpdesk' kind of entity, that can be a shared account by a couple of helpers, instead of J's personal account.

**Comment by agent725** [comment]
user 'J' removed, and helpdesk user added
